// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvnyppzfmdzwfxqrkymr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2bnlwcHpmbWR6d2Z4cXJreW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODEzMTAsImV4cCI6MjA1ODg1NzMxMH0.VvglrmyXBL_MRxrLUmx0qI5ThYDz9kn6RsT7OUhpahM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);